# Generated by Django 3.2.5 on 2021-07-19 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210719_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Exists', 'Exists'), ('Not Exists', 'Not Exists')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('fileCount', models.SmallIntegerField(null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('WIP', 'WIP')], max_length=200, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employee')),
                ('projectName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.project')),
            ],
        ),
    ]
