# Generated by Django 3.2.5 on 2021-07-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210720_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employee'),
        ),
    ]
