# Generated by Django 3.2.5 on 2021-07-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_tracker_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthandle',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.client'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='client',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='employee',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='job',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
