# Generated by Django 3.2.5 on 2021-07-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210720_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='job',
        ),
    ]
