# Generated by Django 3.2.5 on 2021-08-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='startTime',
        ),
        migrations.AddField(
            model_name='tracker',
            name='spentTime',
            field=models.TimeField(default='00:00', null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='workedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
