# Generated by Django 3.2.5 on 2021-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210804_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='spentTime',
        ),
        migrations.AddField(
            model_name='tracker',
            name='spentTimeHr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='spentTimeMin',
            field=models.IntegerField(null=True),
        ),
    ]
