# Generated by Django 3.2.5 on 2021-08-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210805_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dor',
            field=models.DateField(null=True),
        ),
    ]
