# Generated by Django 3.2.5 on 2022-10-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20210817_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
    ]
